controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    effort_controllers:
      type: effort_controllers/JointGroupEffortController
    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_hip_joint
      - right_hip_joint
      - left_knee_joint
      - right_knee_joint
      - world_to_backpack
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

effort_controllers:
  ros__parameters:
    joints:
      - left_hip_joint
      - right_hip_joint
      - left_knee_joint
      - right_knee_joint
      - world_to_backpack
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
      